manage_systerm/comments/urls.py
from django.urls import path

from . import views
app_name = 'comments'

urlpatterns = [
    path('comment/<int:article_pk>', views.submit_comment, name='comment'),
]

manage_systerm/myblog/urls.py
from django.urls import path

from . import views
app_name = 'myblog'
urlpatterns = [
    path('', views.index, name='index'),
    path('article/<int:pk>/', views.detail, name='detail')
]

manage_systerm/start/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myblog.urls')),
    path('comments/', include('comments.urls'))

]

manage_systerm/comments/models.py
from django.db import models

# Create your models here.
from django.utils import timezone


class Comment(models.Model):
    """
    评论
    """
    name = models.CharField('名字', max_length=50)
    email = models.EmailField('邮箱', blank=True)
    url = models.URLField('网址', blank=True)
    text = models.TextField('内容')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    article = models.ForeignKey('myblog.Article', verbose_name='文章', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

manage_systerm/myblog/models.py
import markdown
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models import CharField, TextField
from django.urls import reverse
from django.utils import timezone
from django.utils.html import strip_tags


class Category(models.Model):
    """
    文章类别
    """
    name = CharField('类别名称', max_length=100)

    class Meta:
        verbose_name = '博客分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    标签类别
    """
    tag_name = CharField('标签名', max_length=100)

    class Meta:
        verbose_name = '博客标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.tag_name


class Article(models.Model):
    """
    文章
    """
    title = CharField('标题', max_length=100)
    content = TextField('内容')
    excerpt = models.CharField('文章摘要', max_length=200, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='文章所属分类')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='文章所属标签')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='文章作者')
    created_time = models.DateTimeField('创建时间', default=timezone.now())
    update_time = models.DateTimeField('更新时间', auto_now=True)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-created_time', 'title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('myblog:detail', kwargs={'pk': self.pk})

    def save(self,*args, **kwargs):
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

        self.excerpt = strip_tags(md.convert(self.content))[:50]
        super().save(*args, **kwargs)

manage_systerm/comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

manage_systerm/comments/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.views.decorators.http import require_POST

from myblog.models import Article
from .forms import CommentForm


@require_POST
def submit_comment(request, article_pk):
    """
    提交评论
    :return:
    """
    article = get_object_or_404(Article, pk=article_pk)

    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)

        comment.article = article
        comment.save()

        messages.add_message(request, messages.SUCCESS, '评论发表成功！', extra_tags='success')
        return redirect(article)

    context = {
        'article': article,
        'form': form
    }
    messages.add_message(request, messages.ERROR, '评论发表失败！请修改表单中的错误后重新提交。', extra_tags='danger')
    return render(request, 'comments/preview.html', context=context)

manage_systerm/myblog/views.py
import re

import markdown
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension

from .models import Article


def index(request):
    """
    首页访问
    :return:
    """
    article_list = Article.objects.all()
    return render(request, 'myblog/index.html', context={
       'article_list': article_list
    })


def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        TocExtension(slugify=slugify),
        'markdown.extensions.toc',
        ])

    article.content = md.convert(article.content)
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    article.toc = m.group(1) if m is not None else ''
    return render(request, 'myblog/detail.html', context={'article': article})

manage_systerm/templates/base.html
<!DOCTYPE html>
<html>
{% load static %}
{% load blog_extra %}
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">


    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

    <style>
    .codehilite {
      padding: 0;
    }

    /* for block of numbers */
    .hljs-ln-numbers {
      -webkit-touch-callout: none;
      -webkit-user-select: none;
      -khtml-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;

      text-align: center;
      color: #ccc;
      border-right: 1px solid #CCC;
      vertical-align: top;
      padding-right: 5px;
    }

    .hljs-ln-n {
      width: 30px;
    }

    /* for block of code */
    .hljs-ln .hljs-ln-code {
      padding-left: 10px;
      white-space: pre;
    }
  </style>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'myblog:index' %}"><b>Keep</b> &amp; Thinking 啊啊啊</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'myblog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>

    {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
        {{ message }}
      </div>
    {% endfor %}
{% endif %}
</div>


<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}

                {% show_recent_articles %}
                {% show_archives %}
                {% show_categories %}
                {% show_tags %}

                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>



<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>
</body>
</html>

manage_systerm/templates/comments/inclusions/_form.html
<form action="{% url 'comments:comment' article.pk %}" method="post" class="comment-form">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-4">
      <label for="{{ form.name.id_for_label }}">{{ form.name.label }}：</label>
      {{ form.name }}
      {{ form.name.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.email.id_for_label }}">{{ form.email.label }}：</label>
      {{ form.email }}
      {{ form.email.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.url.id_for_label }}">{{ form.url.label }}：</label>
      {{ form.url }}
      {{ form.url.errors }}
    </div>
    <div class="col-md-12">
      <label for="{{ form.text.id_for_label }}">{{ form.text.label }}：</label>
      {{ form.text }}
      {{ form.text.errors }}
      <button type="submit" class="comment-btn">发表</button>
    </div>
  </div>    <!-- row -->
</form>

manage_systerm/templates/comments/inclusions/_list.html
<h5>评论列表，共 <span>{{ comment_count }}</span> 条评论</h5>
<ul class="comment-list list-unstyled">
  {% for comment in comment_list %}
    <li class="comment-item">
      <span class="nickname">{{ comment.name }}</span>
      <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
      <div class="text">
        {{ comment.text|linebreaks }}
      </div>
    </li>
  {% empty %}
    暂无评论
  {% endfor %}
</ul>

manage_systerm/templates/comments/preview.html
{% extends 'base.html' %}
{% load comments_extras %}
 
{% block main %}
  {% show_comment_form article form %}
{% endblock main %}

manage_systerm/templates/myblog/detail.html
{% extends 'base.html' %}
{% load comments_extras %}
{% block main %}
    <article class="article article-{{ article.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ article.title }}</h1>
            <div class="entry-meta">
                <span class="article-date"><a href="#"><time class="entry-date"
                                                        datetime="{{ article.created_time }}">{{ article.created_time }}</time></a></span>
                <span class="article-author"><a href="#">{{ article.author }}</a></span>
                <span class="comments-link"><a href="{{ article.get_absolute_url }}#comment-area">{{ article.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">588 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ article.content | safe }}
        </div>
    </article>
    </br>
    <section class="comment-area" id="comment-area">
        <h4>发表评论</h4>
        {% show_comment_form  article %}
        <div class="comment-list-panel">
            {% show_comments article %}
        </div>
    </section>
{% endblock main %}
{% block toc %}
    {% if article.toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        <div class="toc">
            <ul>
                 {{ article.toc | safe }}
            </ul>
        </div>

    </div>
    {% endif %}
{% endblock toc %}

manage_systerm/templates/myblog/inclusions/_archives.html
<div class="widget widget-archives">
  <h3 class="widget-title">归档</h3>
  <ul>
    {% for date in date_list %}
      <li>
        <a href="#">{{ date.year }} 年 {{ date.month }} 月</a>
      </li>
    {% empty %}
      暂无归档！
    {% endfor %}
  </ul>
</div>

manage_systerm/templates/myblog/inclusions/_categories.html
<div class="widget widget-category">
  <h3 class="widget-title">分类</h3>
  <ul>
    {% for category in category_list %}
      <li>
        <a href="#">{{ category.name }} <span class="article-count">({{ length }})</span></a>
      </li>
    {% empty %}
      暂无分类！
    {% endfor %}
  </ul>
</div>

manage_systerm/templates/myblog/inclusions/_recent_articles.html
<div class="widget widget-recent-posts">
  <h3 class="widget-title">最新文章</h3>
  <ul>
    {% for article in recent_article_list %}
      <li>
        <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
      </li>
    {% empty %}
      暂无文章！
    {% endfor %}
  </ul>
</div>

manage_systerm/templates/myblog/inclusions/_tags.html
<div class="widget widget-tag-cloud">
  <h3 class="widget-title">标签云</h3>
  <ul>
    {% for tag in tag_list %}
      <li>
        <a href="#">{{ tag.tag_name }}</a>
      </li>
    {% empty %}
      暂无标签！
    {% endfor %}
  </ul>
</div>

manage_systerm/templates/myblog/index.html
{% extends 'base.html' %}

{% block main %}
    {% for article in article_list %}
        <article class="article article-1">
            <article class="article article-{{ article.pk }}">
                <h1 class="entry-title">
                    <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
                </h1>
                <div class="entry-meta">

                    <span class="article-date"><a href="#"><time class="entry-date"
                                                              datetime="2012-11-09T23:15:57+00:00">{{ article.created_time }}</time></a></span>
                    <span class="article-author"><a href="#">{{ article.author }}</a></span>
                    <span class="comments-link"><a href="{{ article.get_absolute_url }}#comment-area">{{ article.comment_set.count }} 评论</a></span>
                    <span class="views-count"><a href="#">588 阅读</a></span>
                </div>

                <div class="entry-content clearfix">
                    <p>{{ article.excerpt }}</p>
                    <div class="read-more cl-effect-14">
                        <a href="{{ article.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                    </div>
                </div>
            </article>
        </article>
    {% empty %}
        <div class="no-article">暂时还没有发布的文章！</div>
    {% endfor %}
    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <div class="pagination">
        <ul>
            <li><a href="">1</a></li>
            <li><a href="">...</a></li>
            <li><a href="">4</a></li>
            <li><a href="">5</a></li>
            <li class="current"><a href="">6</a></li>
            <li><a href="">7</a></li>
            <li><a href="">8</a></li>
            <li><a href="">...</a></li>
            <li><a href="">11</a></li>
        </ul>
    </div>
{% endblock main %}